apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaXRsYWJyZWdpc3RyeS5jYWxsdG91Y2gubmV0IjogewoJCQkiYXV0aCI6ICJiMjFwYTJWdWFXNWhPbEJTWjBkdGN6TnciCgkJfSwKCQkiZ2hjci5pbyI6IHsKICAgICAgICAgICAgICAgICAgICAgICAiYXV0aCI6ICJiV2xyWlc1cGJtRTZaMmh3WDJsVWRqSlZPVUpMZW1KTVowMHhSV2RLVDA1R1NuZEtXVXRFYVdoSFFqRTBhbXQ0ZGc9PSIKICAgICAgICAgICAgICAgIH0KCX0KfQo=
type: kubernetes.io/dockerconfigjson
