server {
    listen 8000 default_server;

    root /var/www/public;

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    access_log /dev/stdout;
    error_log /dev/stderr;

    location /health {
        return 200;
    }

    location /api {
        fastcgi_split_path_info ^(/api)(.*)$;
        fastcgi_pass localhost:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_NAME /index.php;
        fastcgi_param SCRIPT_FILENAME $document_root/index.php;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param PATH_PREFIX $fastcgi_script_name;
    }
}
